### ISSUE TITLE
it seems that it still miss something

### ISSUE THREAD

**Issue by cst781** [gentaiscool/end2end-asr-pytorch#8]
I encounter such problem below:
ModuleNotFoundError: No module named 'models.asr.las'

**Comment by gentaiscool** [comment]
Yes, I deleted some files before and I missed that one. I will update the code. Thanks

**Comment by gentaiscool** [comment]
I fixed the bug and tested the code again. You should be able to run it. #9

**Comment by cst781** [comment]
when I run your multi-gpu command, it said that all tensors must be on devices0, and when change the number of gpu to four, it said forward ()missing 3 required positional arguments : 'padded_input', 'input_lengths', and 'padded_target', it still exists some problem.

**Comment by gentaiscool** [comment]
I am going to check the code. Thanks

**Comment by cst781** [comment]
also could i  ask you that it seems that I couldn't run your code in one gpu, I encounter such problem below.
  File "train.py", line 117, in <module>
    trainer.train(model, train_loader, train_sampler, valid_loader_list, opt, loss_type, start_epoch, num_epochs, label2id, id2label, metrics)
  File "/asr-data/chenshaotian/end2end-asr-pytorch/trainer/asr/trainer.py", line 165, in train
    total_valid_loss/(i+1), total_valid_cer*100/total_valid_char))
ZeroDivisionError: division by zero

**Comment by gentaiscool** [comment]
@cst781 Are you training on AiShell-1 dataset? I just figured out, I forget to remove break in the code (already updated the code #10). I am still checking the multi-GPU training code, I will let you know soon.

**Comment by cst781** [comment]
Thank you. I trained on the librispeech dataset. I will take a try.
